global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # OpenTelemetry Collector metrics for GitHub Actions observability
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['collector:9464']
    scrape_interval: 15s
    metrics_path: '/metrics'
    scrape_timeout: 10s
